const lang = [
    {//English
        gr6sched: "RMS 6",
        gr7sched: "RMS 7",
        gr8sched: "RMS 8",
        ths1: "THS 1st lunch",
        ths2: "THS 2nd lunch",
        paused: "Paused",
        dark: "Dark Mode",
        light: "Light Mode",
        colors: "COLORS",
        ytest: "Testing",
        ntest: "Normal",
        learnt: "Learn't",
        loading: "Loading...",
        ussa: " until school starts again",
        summer: "Summer!",
        dwtd: "% done with the day",
        assembly: "Assembly",
    },
    {//Spanish
        gr6sched: "EMR 6",
        gr7sched: "EMR 7",
        gr8sched: "EMR 8",
        ths1: "EST 1er almuerzo",
        ths2: "EST 2do almuerzo", 
        paused: "Pausado",
        dark: "Modo oscuro",
        light: "Modo claro",
        colors: "COLORES",
        ytest: "Evaluando",
        ntest: "Normal",
        learnt: "No escuela",
        loading: "Cargando...",
        ussa: " hasta que la escuela empiece",
        summer: "¡Verano!",
        dwtd: "% del día ha pasado",
        assembly: "Reunión",
    },
    {//French
        gr6sched: "CR 6",
        gr7sched: "CR 5",
        gr8sched: "CR 4",
        ths1: "LT 1re déjeuner",
        ths2: "LT 2de déjeuner",
        paused: "Arrêté",
        dark: "Mode foncé",
        light: "Mode claire",
        colors: "COULEURS",
        ytest: "En train d'interroger",
        ntest: "Normal",
        learnt: "Pas de l'école",
        loading: "En chargeant...",
        ussa: " jusqu'à ce que l'école commence",
        summer: "Été !",
        dwtd: " % du jour a passé",
        assembly: "Réunion",
    }
]